name: Deploy to Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Lightsail
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /opt/bitnami/apache/apps/
          sudo chown -R bitnami:daemon /opt/bitnami/apache/apps/
          sudo chmod -R 775 /opt/bitnami/apache/apps/
          
          # Remove all files except storage, config directories and .env file
          sudo find . -maxdepth 1 ! -name '.' ! -name 'storage' ! -name 'config' ! -name '.env' -exec rm -rf {} +
          
    - name: Copy files conditionally
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /opt/bitnami/apache/apps/
          
          # Copy files from repository via git
          git clone https://github.com/${{ github.repository }} /tmp/repo
          cd /tmp/repo/apps/
          
          # Copy all files except storage, config, .env if they exist on server
          for item in *; do
            if [[ "$item" == "storage" || "$item" == "config" || "$item" == ".env" ]]; then
              if [[ ! -e "/opt/bitnami/apache/apps/$item" ]]; then
                sudo cp -r "$item" "/opt/bitnami/apache/apps/"
              fi
            else
              sudo cp -r "$item" "/opt/bitnami/apache/apps/"
            fi
          done
          
          # Cleanup
          rm -rf /tmp/repo
        
    - name: Restart Apache
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          sudo chown -R bitnami:daemon /opt/bitnami/apache/apps/
          sudo chmod -R 755 /opt/bitnami/apache/apps/
          
          # Backup config if not exists
          if [ ! -f /opt/bitnami/apache/conf/httpd.conf.backup ]; then
            sudo cp /opt/bitnami/apache/conf/httpd.conf /opt/bitnami/apache/conf/httpd.conf.backup
          fi
          
          # Update DocumentRoot (idempotent)
          sudo sed -i 's|DocumentRoot "/opt/bitnami/apache/htdocs"|DocumentRoot "/opt/bitnami/apache/apps"|g' /opt/bitnami/apache/conf/httpd.conf
          sudo sed -i 's|<Directory "/opt/bitnami/apache/htdocs">|<Directory "/opt/bitnami/apache/apps">|g' /opt/bitnami/apache/conf/httpd.conf
          
          # Test Apache config
          sudo /opt/bitnami/apache/bin/httpd -t
          
          # Restart Apache
          sudo /opt/bitnami/ctlscript.sh restart apache