name: Deploy to Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Lightsail
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          # Create apps and backoffice directories if they don't exist
          sudo mkdir -p /opt/bitnami/apache/apps/
          sudo mkdir -p /opt/bitnami/apache/apps/backoffice/
          cd /opt/bitnami/apache/apps/
          sudo chown bitnami:root /opt/bitnami/apache/apps/
          sudo chmod 775 /opt/bitnami/apache/apps/
          
          # Remove all files except backoffice directory
          sudo find . -maxdepth 1 ! -name '.' ! -name 'backoffice' -exec rm -rf {} +
          
          # Cleanup inside backoffice directory (preserve storage, config, .env)
          cd backoffice/
          sudo find . -maxdepth 1 ! -name '.' ! -name 'storage' ! -name 'config' ! -name '.env' -exec rm -rf {} +
          cd ..
          
    - name: Copy non-backoffice files
      run: |
        tar --exclude='apps/backoffice' -czf apps-no-backoffice.tar.gz apps/
        scp -o StrictHostKeyChecking=no -i <(echo "${{ secrets.LIGHTSAIL_SSH_KEY }}") apps-no-backoffice.tar.gz bitnami@${{ secrets.LIGHTSAIL_HOST }}:/tmp/
        ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.LIGHTSAIL_SSH_KEY }}") bitnami@${{ secrets.LIGHTSAIL_HOST }} "cd /tmp && tar -xzf apps-no-backoffice.tar.gz && cp -r apps/* /opt/bitnami/apache/apps/ && rm -rf apps apps-no-backoffice.tar.gz"
        
    - name: Copy backoffice files conditionally
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /opt/bitnami/apache/apps/backoffice/
          
          # Copy storage, config, .env only if they don't exist
          if [[ ! -e "storage" ]]; then
            scp -r -o StrictHostKeyChecking=no bitnami@localhost:/tmp/checkout/apps/backoffice/storage . 2>/dev/null || echo "No storage in source"
          fi
          if [[ ! -e "config" ]]; then
            scp -r -o StrictHostKeyChecking=no bitnami@localhost:/tmp/checkout/apps/backoffice/config . 2>/dev/null || echo "No config in source"
          fi
          if [[ ! -e ".env" ]]; then
            scp -o StrictHostKeyChecking=no bitnami@localhost:/tmp/checkout/apps/backoffice/.env . 2>/dev/null || echo "No .env in source"
          fi
          
    - name: Copy other backoffice files
      run: |
        tar --exclude='apps/backoffice/storage' --exclude='apps/backoffice/config' --exclude='apps/backoffice/.env' -czf backoffice-files.tar.gz apps/backoffice/
        scp -o StrictHostKeyChecking=no -i <(echo "${{ secrets.LIGHTSAIL_SSH_KEY }}") backoffice-files.tar.gz bitnami@${{ secrets.LIGHTSAIL_HOST }}:/tmp/
        ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.LIGHTSAIL_SSH_KEY }}") bitnami@${{ secrets.LIGHTSAIL_HOST }} "cd /tmp && tar -xzf backoffice-files.tar.gz && cp -r apps/backoffice/* /opt/bitnami/apache/apps/backoffice/ && rm -rf apps backoffice-files.tar.gz"
        
    - name: Process vhosts files
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          # Create apache conf vhosts directory
          sudo mkdir -p /opt/bitnami/apache/conf/vhosts/
          
          # Process vhosts files if they exist
          if [ -d "/opt/bitnami/apache/apps/vhosts" ]; then
            cd /opt/bitnami/apache/apps/vhosts/
            for file in *; do
              if [ -f "$file" ] && [ ! -f "/opt/bitnami/apache/conf/vhosts/$file" ]; then
                sudo cp "$file" "/opt/bitnami/apache/conf/vhosts/"
                echo "Copied $file to apache conf vhosts"
              fi
            done
            
            # Remove vhosts directory from apps
            cd ..
            sudo rm -rf vhosts/
          fi
        
    - name: Restart Apache
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: bitnami
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          # Set bitnami:root permissions for Apache directories
          sudo chown bitnami:root /opt/bitnami/apache/apps/
          sudo chown -R bitnami:root /opt/bitnami/apache/conf/
          sudo chown -R bitnami:root /opt/bitnami/apache/htdocs/
          sudo mkdir -p /opt/bitnami/apache/office/
          sudo chown -R bitnami:root /opt/bitnami/apache/office/
          
          # Set bitnami:bitnami for all content inside apps
          sudo chown -R bitnami:bitnami /opt/bitnami/apache/apps/*
          sudo chmod -R 755 /opt/bitnami/apache/apps/
          
          # Backup config if not exists
          if [ ! -f /opt/bitnami/apache/conf/httpd.conf.backup ]; then
            sudo cp /opt/bitnami/apache/conf/httpd.conf /opt/bitnami/apache/conf/httpd.conf.backup
          fi
          
          # Update DocumentRoot (idempotent)
          sudo sed -i 's|DocumentRoot "/opt/bitnami/apache/htdocs"|DocumentRoot "/opt/bitnami/apache/apps"|g' /opt/bitnami/apache/conf/httpd.conf
          sudo sed -i 's|<Directory "/opt/bitnami/apache/htdocs">|<Directory "/opt/bitnami/apache/apps">|g' /opt/bitnami/apache/conf/httpd.conf
          
          # Test Apache config
          sudo /opt/bitnami/apache/bin/httpd -t
          
          # Restart Apache
          sudo /opt/bitnami/ctlscript.sh restart apache